apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: petclinic-cluster
  region: ap-south-1
  version: "1.30"

availabilityZones:
  - ap-south-1a
  - ap-south-1b

managedNodeGroups:
  - name: petclinic-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    privateNetworking: false
